version: "3"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./app
    container_name: app
    ports:
      - "3000:3000"  # Map host port 3000 to container port 3000
    restart: always
    volumes:
      - .:/app
      - /app/app/node_modules
  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./gateway
    depends_on:
      - users
      - orders
      - app
      - common
    ports:
      - "80:80"  # Map host port 80 to container port 80
  users:
    build:
      dockerfile: Dockerfile
      context: ./users
    container_name: users
    ports:
      - "3001:3001"  # Map host port 3001 to container port 3001
    restart: always
    volumes:
      - .:/app
      - /app/users/node_modules
  orders:
    build:
      dockerfile: Dockerfile
      context: ./orders
    container_name: orders
    ports:
      - "3002:3002"  # Map host port 3002 to container port 3002
    restart: always
    volumes:
      - .:/app
      - /app/orders/node_modules